export enum SuccessMessage {
  USER_REGISTERED = "USER_REGISTERED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",

} 
